############ Experimental Settings ########################################################
fps: 30                                       # camera frame rate (units: frames/sec)
camera_scale: 60                              # pixel/cm
input_data_path: "data/task1_etho"            # folder path of body pose H5 files
result_path: "results/task1_etho"             # folder path of analyzed results and figures

############ Skeleton ########################################################
skeleton: [
    [0,1],[0,2],[1,3],[2,3],
    [3,4],[3,5],[5,6],[4,6]]
skeleton_color: [
    'tab:blue','tab:blue','tab:blue','tab:blue',
    'tab:blue','tab:blue','tab:blue','tab:blue']

skeleton_fill: [
    {
        "trapezoid":[0,1,3,2],
        "fill": "blue"
    },
    {
        "trapezoid":[3,4,6,5],
        "fill": "blue"
    }]

likelihood_thresh: 0.98
marker_thresh: 1
bad_fr_pad: 20

########### Signals ########################################################
bp_center: 3
bp_scale: [3,6]
bp_rotate: 6
scale: 121

########### Postural Features ########################################################
# Marker Position
include_marker_postural: False
include_marker_kinematic: False
markers: [0,1,3, 5,6]
marker_kinematic_pca_components: 170
marker_labels: ['nose', 'left ear', 'right ear', 'neck', 'left hip', 'right hip', 'tail']

# Joint Angle
include_angle_postural: False
include_angle_kinematic: False
angle_kinematic_pca_components: 60
angles:
  # 0 - NOSE
  - {"a": 2, "b": 0, "c": 1, "method": 0}
  # 1 - LEFT EAR
  - {"a": 0, "b": 1, "c": 3, "method": 1}
  # 2 - RIGHT EAR
  - {"a": 3, "b": 2, "c": 0, "method": 1}
  # 3 - HEAD NECK
  - {"a": 1, "b": 3, "c": 2, "method": 1}
  # 4 - HEAD
  - {"a": 0, "b": 3, "c": 6, "method": 1}
  # 5 - BODY NECK
  - {"a": 5, "b": 3, "c": 4, "method": 0}
  # 6 - LEFT HIP
  - {"a": 3, "b": 4, "c": 6, "method": 1}
  # 7 - RIGHT HIP
  - {"a": 6, "b": 5, "c": 3, "method": 1}
  # 8 - TAIL
  - {"a": 4, "b": 6, "c": 5, "method": 1}
angle_labels:
  - nose
  - left ear
  - right ear
  - head neck
  - head
  - body neck
  - left hip
  - right hip
  - tail

# Limb Length
include_limb_postural: False
include_limb_kinematic: False
limb_kinematic_pca_components: 30
limbs:
  - [0,3]
  - [1,2]
  - [3,6]
  - [4,5]

limb_labels:
  - head x
  - head y
  - body x
  - body y
limb_threshold:
  - 50
  - 50
  - 50
  - 50

include_all_postural: False
include_all_kinematic: False
include_all_features: True

# Morlet Wavelet Transformation
w: 5
f_bin: 20       # number of frequency bin
f_min: 1

# Kinematic & Postural Influence
postural_weight: 4 # try 1.5, 2, 2.5, 3
kinematic_weight: 1

# UMAP
n_components: 2
n_neighbors: 60
n_epochs: 10000 
min_dist: 0.0001
spread: 1.0 # 3.0
negative_sample_rate: 5
init: "spectral"
repulsion_strength: 3.0 # 10

# Clustering (HDBSCAN, GMM)

# Figures
save_video_path: "videos/task1_etho"
num_sample_videos: 3
max_video_length: 80

# Save
save_bodypoints: True
save_scaled_bodypoints: False
save_body_orientation_angles: False
save_rotated_bodypoints: True
save_embeddings: True
save_clusters: False


### Bad Frames ###
# x_bound_std: 2.5
# y_bound_std: 2.5
# velocity_thresh: 40  # pixel/frame; a little over half the body length
# max_limb_length: 35  # 25
# TODO set threshold based on every video

