### Experimental Settings ###
fps: 50          # camera frame rate (units: frames/sec)
camera_scale: 60 # pixel/cm
input_data_path: "data/ant_field_final"
result_path: "results/final"

### Bad Frames ###
x_bound_std: 2.5
y_bound_std: 2.5
velocity_thresh: 40  # pixel/frame; a little over half the body length
# max_limb_length: 35  # 25
# TODO set threshold based on every video

### Skeleton ###
skeleton: [
    [0,1],[1,2],[2,3],
    [4,5],[5,6],[6,7],
    [8,9],[9,10],
    [11,12],[12,13],
    [14,15],[15,16],
    [17,18],[18,19],[19,20],
    [21,22],[22,23],
    [24,25],[25,26],
    [27,28],[28,29]
]
skeleton_color: [
    'tab:blue','tab:blue','tab:blue',
    'tab:orange','tab:orange','tab:orange',
    'tab:green','tab:green',
    'tab:red','tab:red',
    'tab:purple','tab:purple',
    'tab:brown','tab:brown','tab:brown',
    'tab:pink','tab:pink',
    'tab:gray','tab:gray',
    'tab:olive','tab:olive']

likelihood_thresh: 0.98
marker_thresh: 1
bad_fr_pad: 20

### Signals ###
bp_center: 2
bp_scale: [1, 2]
bp_rotate: 1
scale: False

### Postural Features ###
# Marker Position
include_marker_postural: False
include_marker_kinematic: False
markers: [0,1,3, 5,6,7, 8,9, 11,12, 14,15, 18,19,20, 21,22, 24,25, 27,28]
marker_kinematic_pca_components: 170
marker_labels: [head, thorax, abdomen, 
(R) Antennae Tip, (R) Antennae Mid, (R) Antennae Base,
(R) FL Tip, (R) FL Mid, (R) ML Tip, (R) ML Mid, (R) HL Tip, (R) HL Mid,
(L) Antennae Tip, (L) Antennae Mid, (L) Antennae Base,
(L) FL Tip, (L) FL Mid, (L) ML Tip, (L) ML Mid, (L) HL Tip, (L) HL Mid]

# Joint Angle
include_angle_postural: False
include_angle_kinematic: False
angle_kinematic_pca_components: 70
angles:
  # HEAD
  - {"a": 0, "b": 1, "c": 2}
  # ABDOMEN
  - {"a": 1, "b": 2, "c": 3}
  # (R) ANTENNAE
  - {"a": 0, "b": 6, "c": 5}
  # (R) ANTENNAE 2
  - {"a": 1, "b": 0, "c": 6}
  # (R) LEGS
  - {"a": 8, "b": 1, "c": 2}
  - {"a": 11, "b": 1, "c": 2}
  - {"a": 14, "b": 2, "c": 1}

  # (L) ANTENNAE
  - {"a": 0, "b": 19, "c": 18}
  # (L) ANTENNAE 2
  - {"a": 1, "b": 0, "c": 19}
  # (L) LEGS
  - {"a": 21, "b": 1, "c": 2}
  - {"a": 24, "b": 1, "c": 2}
  - {"a": 27, "b": 2, "c": 1}
angle_labels:
  - Head
  - Abdomen
  - (R) Antennae
  - (R) Antennae 2 
  - (R) Front Leg
  - (R) Mid Leg
  - (R) Hind Leg
  - (L) Antennae 
  - (L) Antennae 2
  - (L) Front Leg
  - (L) Mid Leg
  - (L) Hind Leg

# Limb Length
include_limb_postural: False
include_limb_kinematic: False
limb_kinematic_pca_components: 40
limbs:
  - [0,1]
  - [1,2]
  - [2,3]
  - [5,6]
  - [6,7]
  - [8,9]
  - [11,12]
  - [14,15]
  - [18,19]
  - [19,20]
  - [21,22]
  - [24,25]
  - [27,28]
limb_labels:
  - Head
  - Thorax
  - Abdomen
  - (R) Antennae Mid-Tip
  - (R) Antennae Base-Mid
  - (R) Front Leg
  - (R) Mid Leg
  - (R) Hind Leg
  - (L) Antennae Mid-Tip
  - (L) Antennae Base-Mid
  - (L) Front Leg
  - (L) Mid Leg
  - (L) Hind Leg
limb_threshold:
  - 15
  - 25
  - 25
  - 15
  - 15
  - 25
  - 25
  - 25
  - 15
  - 15
  - 25
  - 25
  - 25

include_all_postural: True
include_all_kinematic: True
include_all_features: True

# Morlet Wavelet Transformation
w: 5
f_bin: 20       # number of frequency bin

# UMAP
n_components: 2
n_neighbors: 40
n_epochs: 10000 
min_dist: 0.001
spread: 1.0 # 3.0
negative_sample_rate: 5
init: "spectral"
repulsion_strength: 3.0 # 10

# Clustering (HDBSCAN, GMM)

# Figures
save_video_path: "videos/round2_legs_antennae"
num_sample_videos: 3
max_video_length: 80

# Save
save_bodypoints: True
save_scaled_bodypoints: True
save_body_orientation_angles: False
save_rotated_bodypoints: True
save_angles: True
save_limbs: True
save_powers: True
save_embeddings: True
save_clusters: False
