name: notebook_analysis
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19=hecd8cb5_1
  - certifi=2020.12.5=py39hecd8cb5_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1j=h9ed2024_0
  - pip=21.0.1=py39hecd8cb5_0
  - python=3.9.2=h88f2d9e_0
  - readline=8.1=h9ed2024_0
  - setuptools=52.0.0=py39hecd8cb5_0
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - tzdata=2020f=h52ac0ba_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - cython==0.29.22
    - hdbscan==0.8.27
    - joblib==1.0.1
    - numpy==1.20.1
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - six==1.15.0
    - threadpoolctl==2.1.0
prefix: /Users/donghur/anaconda3/envs/notebook_analysis
